import { BrandKit } from '../types'

export async function exportBrandGuidePdf(kit: BrandKit, brandName: string) {
  // Dynamically import to avoid bundle bloat
  const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
    import('jspdf'),
    import('html2canvas'),
  ])

  // Build a temporary off-screen brand guide element
  const el = document.createElement('div')
  el.id = '__brand-guide-export__'
  el.style.cssText = `
    position: fixed; top: -9999px; left: -9999px;
    width: 794px; min-height: 1123px;
    background: #060911; color: white;
    font-family: '${kit.font}', sans-serif;
    padding: 64px; box-sizing: border-box;
  `

  el.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:48px;padding-bottom:32px;border-bottom:1px solid rgba(255,255,255,0.08)">
      <div>
        <div style="font-size:32px;font-weight:900;background:linear-gradient(135deg,${kit.primary},${kit.accent});-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:4px">${brandName}</div>
        <div style="font-size:13px;color:rgba(255,255,255,0.4);letter-spacing:0.08em;text-transform:uppercase">Brand Guidelines</div>
      </div>
      <div style="font-size:11px;color:rgba(255,255,255,0.25);text-align:right">
        Generated by Move AI Studio<br>${new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })}
      </div>
    </div>

    <!-- Colour Palette -->
    <div style="margin-bottom:48px">
      <div style="font-size:11px;font-weight:700;color:rgba(255,255,255,0.3);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:20px">Colour Palette</div>
      <div style="display:flex;gap:16px">
        ${[
          { hex: kit.primary, label: 'Primary', role: 'CTAs, active states, key UI' },
          { hex: kit.secondary, label: 'Secondary', role: 'Gradients, hover states' },
          { hex: kit.accent, label: 'Accent', role: 'Highlights, badges, icons' },
          { hex: '#060911', label: 'Background', role: 'Dark base surface' },
          { hex: '#ffffff', label: 'Text', role: 'Primary text colour' },
        ].map(c => `
          <div style="flex:1">
            <div style="height:80px;border-radius:12px;background:${c.hex};margin-bottom:10px;border:1px solid rgba(255,255,255,0.08)"></div>
            <div style="font-size:13px;font-weight:700;color:white;margin-bottom:2px">${c.label}</div>
            <div style="font-size:11px;color:rgba(255,255,255,0.4);font-family:monospace;margin-bottom:4px">${c.hex.toUpperCase()}</div>
            <div style="font-size:10px;color:rgba(255,255,255,0.3)">${c.role}</div>
          </div>
        `).join('')}
      </div>
    </div>

    <!-- Typography -->
    <div style="margin-bottom:48px;padding:32px;border-radius:16px;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06)">
      <div style="font-size:11px;font-weight:700;color:rgba(255,255,255,0.3);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:24px">Typography — ${kit.font}</div>
      <div style="font-size:48px;font-weight:900;color:white;line-height:1;margin-bottom:8px;font-family:'${kit.font}',sans-serif">Heading One</div>
      <div style="font-size:32px;font-weight:800;color:white;margin-bottom:8px;font-family:'${kit.font}',sans-serif">Heading Two</div>
      <div style="font-size:20px;font-weight:700;color:rgba(255,255,255,0.8);margin-bottom:12px;font-family:'${kit.font}',sans-serif">Heading Three</div>
      <div style="font-size:15px;color:rgba(255,255,255,0.6);line-height:1.7;margin-bottom:8px;font-family:'${kit.font}',sans-serif">Body — The quick brown fox jumps over the lazy dog. Use this typeface across all digital touchpoints for consistency.</div>
      <div style="font-size:12px;color:rgba(255,255,255,0.4);font-family:'${kit.font}',sans-serif">Caption — Supporting detail text, labels, metadata</div>
    </div>

    <!-- Brand Info -->
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:48px">
      <div style="padding:24px;border-radius:14px;background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06)">
        <div style="font-size:11px;font-weight:700;color:rgba(255,255,255,0.3);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:12px">Industry</div>
        <div style="font-size:18px;font-weight:700;color:white">${kit.industry}</div>
      </div>
      <div style="padding:24px;border-radius:14px;background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06)">
        <div style="font-size:11px;font-weight:700;color:rgba(255,255,255,0.3);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:12px">Brand Tone</div>
        <div style="font-size:18px;font-weight:700;color:white">${kit.tone}</div>
      </div>
    </div>

    <!-- Buttons -->
    <div style="margin-bottom:48px">
      <div style="font-size:11px;font-weight:700;color:rgba(255,255,255,0.3);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:20px">Button Styles</div>
      <div style="display:flex;gap:14px;align-items:center;flex-wrap:wrap">
        <div style="padding:12px 24px;border-radius:99px;background:linear-gradient(135deg,${kit.primary},${kit.secondary});color:white;font-weight:700;font-size:14px;font-family:'${kit.font}',sans-serif">Primary CTA</div>
        <div style="padding:12px 24px;border-radius:99px;border:1.5px solid ${kit.accent};color:${kit.accent};font-weight:600;font-size:14px;font-family:'${kit.font}',sans-serif">Secondary</div>
        <div style="padding:12px 24px;border-radius:99px;border:1.5px solid rgba(255,255,255,0.2);color:rgba(255,255,255,0.6);font-weight:600;font-size:14px;font-family:'${kit.font}',sans-serif">Ghost</div>
      </div>
    </div>

    <!-- Footer -->
    <div style="margin-top:auto;padding-top:24px;border-top:1px solid rgba(255,255,255,0.06);display:flex;justify-content:space-between;align-items:center">
      <div style="font-size:11px;color:rgba(255,255,255,0.2)">© ${new Date().getFullYear()} ${brandName}. Confidential brand document.</div>
      <div style="font-size:11px;color:rgba(255,255,255,0.2)">Built with <span style="color:${kit.accent}">Move AI Studio</span></div>
    </div>
  `

  document.body.appendChild(el)

  try {
    const canvas = await html2canvas(el, {
      backgroundColor: '#060911',
      scale: 2,
      useCORS: true,
      logging: false,
    })

    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: 'a4' })
    const pageW = pdf.internal.pageSize.getWidth()
    const pageH = (canvas.height / canvas.width) * pageW

    pdf.addImage(imgData, 'PNG', 0, 0, pageW, pageH)
    pdf.save(`${brandName.toLowerCase().replace(/\s+/g, '-')}-brand-guide.pdf`)
  } finally {
    document.body.removeChild(el)
  }
}
